#ifndef ISR80H_H
#define ISR80H_H

enum Systemcommands
{
    SYSTEM_COMMAND0_SUM,
    SYSTEM_COMMAND1_PRINT,
    SYSTEM_COMMAND2_GETKEY,
    SYSTEM_COMMAND3_PUTCHAR,
    SYSTEM_COMMAND4_MALLOC,
    SYSTEM_COMMAND5_FREE,
    SYSTEM_COMMAND6_PROCESS_LOAD_START,
    SYSTEM_COMMAND7_INVOKE_SYSTEM_COMMAND,
    SYSTEM_COMMAND8_GET_PROGRAM_ARGUMENTS,
    SYSTEM_COMMAND9_EXIT,
    SYSTEM_COMMAND10_FOPEN,
    SYSTEM_COMMAND11_FCLOSE,
    SYSTEM_COMMAND12_FREAD,
    SYSTEM_COMMAND13_FSEEK,
    SYSTEM_COMMAND14_FSTAT,
    SYSTEM_COMMAND15_REALLOC,
    SYSTEM_COMMAND16_WINDOW_CREATE,
    SYSTEM_COMMAND17_SYSOUT_TO_WINDOW,
    SYSTEM_COMMAND18_GET_WINDOW_EVENT,
    SYSTEM_COMMAND19_WINDOW_GRAPHICS_GET,
    SYSTEM_COMMAND20_GRAPHICS_PIXELS_BUFFER_GET,
    SYSTEM_COMMAND21_WINDOW_REDRAW,
};

void isr80h_register_commands();

#endif
