#ifndef CONFIG_H
#define CONFIG_H

#define MARROWOS_TOTAL_INTERRUPTS 512
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

// 100MB heap size;
#define MARROWOS_HEAP_SIZE_BYTES 104857600
#define MARROWOS_HEAP_BLOCK_SIZE 4096

// 0x01000000 = 16mb th location in RAM, refer osdev.org/Memory_Map
#define MARROWOS_HEAP_ADDRESS 0x01000000

// refer osdev.org to where this address came from ?
#define MARROWOS_HEAP_TABLE_ADDRESS 0x00007E00

// sector size in normal hard disk
#define MARROWOS_SECTOR_SIZE 512

// total file systems supported by our kernel
#define MARROWOS_MAX_FILESYSTEMS 12

#define MARROWOS_MAX_FILE_DESCRIPTORS 512

#define MARROWOS_MAX_PATH 108

#define MARROWOS_TOTAL_GDT_SEGMENTS 6

#define MARROWOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define MARROWOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define MARROWOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define MARROWOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END MARROWOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - MARROWOS_USER_PROGRAM_STACK_SIZE

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#define MARROWOS_MAX_PROGRAM_ALLOCATION 1024

#define MARROWOS_MAX_PROCESSES 12

#define MARROWOS_MAX_ISR80H_COMMANDS 1024

#endif
