#ifndef CONFIG_H
#define CONFIG_H

#define MARROWOS_TOTAL_INTERRUPTS 512
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define KERNEL_LONG_MODE_CODE_SELECTOR 0x18

#define KERNEL_LONG_MODE_CODE_GDT_INDEX 3
#define KERNEL_LONG_MODE_DATA_GDT_INDEX 4
#define KERNEL_LONG_MODE_TSS_GDT_INDEX 7

#define TSS_DESCRIPTOR_TYPE 0x89 // 0x9 = 64-bit, bit 7 present

// Where to find the E820 records
#define MARROWOS_MEMORY_MAP_LOCATION 0x7e00

// 16 Bit number defining the total number of loaded
// entries.
#define MARROWOS_MEMORY_MAP_TOTAL_ENTRIES_LOCATION 0x7DFE

// 100MB heap size;
#define MARROWOS_HEAP_MINIMUM_SIZE_BYTES 104857600
#define MARROWOS_HEAP_BLOCK_SIZE 4096

// The minimal address the heap can point at, ensuring
// that the kernel does not get overwritten
#define MARROWOS_MINIMAL_HEAP_ADDRESS 0x01100000 // location - 17mb

// This is a minimal heap table starting address
#define MARROWOS_MINIMAL_HEAP_TABLE_ADDRESS 0x01000000 // table location - 16mb

#define MARROWOS_MINIMAL_HEAP_TABLE_SIZE MARROWOS_MINIMAL_HEAP_ADDRESS - MARROWOS_MINIMAL_HEAP_TABLE_ADDRESS // table size is (1mb)

// sector size in normal hard disk
#define MARROWOS_SECTOR_SIZE 512

// total file systems supported by our kernel
#define MARROWOS_MAX_FILESYSTEMS 12

#define MARROWOS_MAX_FILE_DESCRIPTORS 512

#define MARROWOS_MAX_PATH 108

#define MARROWOS_TOTAL_GDT_SEGMENTS 6

#define MARROWOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define MARROWOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define MARROWOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define MARROWOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END MARROWOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - MARROWOS_USER_PROGRAM_STACK_SIZE

// Selector | RPL 3. Matches kernel.asm GDT:
//   0x28 user code 0xFA  →  0x28|3 = 0x2B
//   0x30 user data 0xF2  →  0x30|3 = 0x33
#define USER_CODE_SEGMENT 0x2B
#define USER_DATA_SEGMENT 0x33

#define MARROWOS_MAX_PROGRAM_ALLOCATION 1024

#define MARROWOS_MAX_PROCESSES 12

#define MARROWOS_MAX_ISR80H_COMMANDS 1024

#define MARROWOS_KEYBOARD_BUFFER_SIZE 1024

#endif
